protected/controllers/PhotoController.php
<?php

class PhotoController extends Controller
{
    /**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','gallery'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array(''),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
	public function actionIndex()
	{
        $galleries = Gallery::model()->findAll();
        
        $this->render('index', array('galleries'=>$galleries));
	}
    
    public function actionGalleries()
	{
        $galleries = Gallery::model()->findAll();
        
        $this->render('index', array('galleries'=>$galleries));
	}
    
    public function actionGallery()
	{
        $this->registerGalleriffic();
        $id = Yii::app()->request->getParam('id');
        $gallery = Gallery::model()->findByPk($id);
        $photos = $gallery->galleryPhotos;
        
        $this->render('view', array('photos'=>$photos));
	}

    
    private function registerGalleriffic()
    {
        Yii::app()->getClientScript()->registerCoreScript('jquery');
        
//        Yii::app()->clientScript->registerCssFile(
//            Yii::app()->baseUrl
//                . '/vendors/galleriffic/css/basic.css'
//        );
//        Yii::app()->clientScript->registerCssFile(
//            Yii::app()->baseUrl
//                . '/vendors/galleriffic/css/black.css'
//        );
        Yii::app()->clientScript->registerScriptFile(
            Yii::app()->baseUrl
                . '/vendors/galleriffic/js/jquery.galleriffic.js',
            CClientScript::POS_HEAD
        );
        Yii::app()->clientScript->registerScriptFile(
            Yii::app()->baseUrl
                . '/vendors/galleriffic/js/jquery.history.js',
            CClientScript::POS_HEAD
        );
        Yii::app()->clientScript->registerScriptFile(
            Yii::app()->baseUrl
                . '/vendors/galleriffic/js/jquery.opacityrollover.js',
            CClientScript::POS_HEAD
        );
        Yii::app()->clientScript->registerCssFile(
            Yii::app()->baseUrl
                . '/css/gallery.css'
        );
        return $this;
    }
    
    
}

protected/views/photo/index.php
<span class="big-icon big-photo"></span><h1>Photo Gallery</h1>

<?php foreach ($galleries as $gallery) { 
    if (!empty($gallery->galleryPhotos)) {
        $image = '_' . $gallery->galleryPhotos[0]->id . '.jpg';
    } else {
        $image = '0.jpg';
    }
    ?>
<div class="gallery-wrapper">
    <a class="gallery-thumb" href ="<?php echo Yii::app()->createUrl('photo/gallery', array('id'=>$gallery->id)); ?>">
        <img src="<?php echo Yii::app()->getBaseUrl(true) . '/gallery/'. $image  ; ?>">
        <span class="gallery-name"><?php echo $gallery->gallery_name; ?></span>
    </a>
</div>
    
<?php } ?>

protected/views/photo/view.php

    
    <div class="navigation-container">
        <div id="thumbs" class="navigation">
            <a class="pageLink prev" style="visibility: hidden;" href="#" title="Previous Page"></a>

            <ul class="thumbs noscript">
                <?php foreach ($photos as $photo) { ?>
                    <li>
                        <a class="thumb" href="<?php echo Yii::app()->getBaseUrl(true) . '/gallery/'. $photo->id .'normal.jpg'; ?>" title="<?php echo $photo->name; ?>">
                            <img src="<?php echo Yii::app()->getBaseUrl(true) . '/gallery/_'. $photo->id .'.jpg'; ?>" alt="<?php echo $photo->name; ?>" />
                        </a>
                        <div class="caption">
                            <div class="image-title"><?php echo $photo->name; ?></div>
                            <div class="image-desc"><?php echo $photo->description; ?></div>
<!--                            <div class="download">
                                <a href="<?php echo Yii::app()->getBaseUrl(true) . '/gallery/'. $photo->id .'.jpg'; ?>">Download Original</a>
                            </div>-->
                        </div>
					</li>
                <?php } ?>
            </ul>
            <a class="pageLink next" style="visibility: hidden;" href="#" title="Next Page"></a>
        </div>
    </div>
    <div class="content">
        <div class="slideshow-container">
            <div id="controls" class="controls"></div>
            <div id="loading" class="loader"></div>
            <div id="slideshow" class="slideshow"></div>
        </div>
        <div id="caption" class="caption-container">
            <div class="photo-index"></div>
        </div>
    </div>
    <!-- End Gallery Html Containers -->


<script type="text/javascript">
        jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li, div.navigation a.pageLink').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
				
				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 10,
					preloadAhead:              1,
					enableTopPager:            false,
					enableBottomPager:         false,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              'Play Slideshow',
					pauseLinkText:             'Pause Slideshow',
					prevLinkText:              '&lsaquo; Previous Photo',
					nextLinkText:              'Next Photo &rsaquo;',
					nextPageLinkText:          'Next &rsaquo;',
					prevPageLinkText:          '&lsaquo; Prev',
					enableHistory:             true,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);

						// Update the photo index display
//						this.$captionContainer.find('div.photo-index')
//							.html('Photo '+ (nextIndex+1) +' of '+ this.data.length);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						var prevPageLink = this.find('a.prev').css('visibility', 'hidden');
						var nextPageLink = this.find('a.next').css('visibility', 'hidden');
						
						// Show appropriate next / prev page links
						if (this.displayedPage > 0)
							prevPageLink.css('visibility', 'visible');

						var lastPage = this.getNumPages() - 1;
						if (this.displayedPage < lastPage)
							nextPageLink.css('visibility', 'visible');

						this.fadeTo('fast', 1.0);
					}
				});

				/**************** Event handlers for custom next / prev page links **********************/

				gallery.find('a.prev').click(function(e) {
					gallery.previousPage();
					e.preventDefault();
				});

				gallery.find('a.next').click(function(e) {
					gallery.nextPage();
					e.preventDefault();
				});

				/****************************************************************************************/

				/**** Functions to support integration of galleriffic with the jquery.history plugin ****/

				// PageLoad function
				// This function is called when:
				// 1. after calling $.historyInit();
				// 2. after calling $.historyLoad();
				// 3. after pushing "Go Back" button of a browser
				function pageload(hash) {
					// alert("pageload: " + hash);
					// hash doesn't contain the first # character.
					if(hash) {
						$.galleriffic.gotoImage(hash);
					} else {
						gallery.gotoIndex(0);
					}
				}

				// Initialize history plugin.
				// The callback is called at once by present location.hash. 
				$.historyInit(pageload, "advanced.html");

				// set onlick event for buttons using the jQuery 1.3 live method
				$("a[rel='history']").live('click', function(e) {
					if (e.button != 0) return true;

					var hash = this.href;
					hash = hash.replace(/^.*#/, '');

					// moves to a new page. 
					// pageload is called at once. 
					// hash don't contain "#", "?"
					$.historyLoad(hash);

					return false;
				});

				/****************************************************************************************/
			});
</script>