protected/models/Comment.php
<?php

/**
 * This is the model class for table "comment".
 *
 * The followings are the available columns in table 'comment':
 * @property integer $id
 * @property string $content
 * @property string $author
 * @property string $email
 * @property integer $post_id
 */
class Comment extends CActiveRecord
{
    
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Comment the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'comment';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('content, author', 'required'),
			array('author', 'length', 'max'=>128),
			array('email', 'length', 'max'=>255),
            array('email', 'email'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, content, author, email, post_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'content' => 'Comment',
			'author' => 'Author',
			'email' => 'Email',
			'post_id' => 'Post',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('content',$this->content,true);
		$criteria->compare('author',$this->author,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('post_id',$this->post_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
    
    
    /**
	 * @param Post the post that this comment belongs to. If null, the method
	 * will query for the post.
	 * @return string the permalink URL for this comment
	 */
	public function getUrl($post=null)
	{
		if($post===null)
			$post=$this->post;
		return $post->url.'#c'.$this->id;
	}
    
    /**
	 * @return string the hyperlink display for the current comment's author
	 */
	public function getAuthorLink()
	{
		if(!empty($this->url))
			return CHtml::link(CHtml::encode($this->author),$this->url);
		else
			return CHtml::encode($this->author);
	}
    
    
    protected function beforeSave()
    {
        if(parent::beforeSave())
        {
            if($this->isNewRecord)
                $this->create_time=date("Y-m-d H:i:s");
            return true;
        }
        else
            return false;
    }

}

protected/controllers/CommentController.php
<?php

class CommentController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Comment;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Comment']))
		{
			$model->attributes=$_POST['Comment'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Comment']))
		{
			$model->attributes=$_POST['Comment'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		//if(!isset($_GET['ajax']))
		//	$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Comment');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Comment('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Comment']))
			$model->attributes=$_GET['Comment'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Comment the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Comment::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Comment $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/blog';
    
    private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'suggestTags', 'ImageList'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete', 'FileUpload', 'ImageUpload'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
    /**
     * Image and file upload with default actions of redactor
     * @return void
     */
    public function actions()
    {
        return array(
            'fileUpload'=>array(
                'class'=>'application.widgets.redactorjs.actions.FileUpload',
                'uploadCreate'=>true,
                'uploadPath' => Yii::app()->basePath.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'public'. DIRECTORY_SEPARATOR .'uploads',
             ),
            'imageUpload'=>array(
                'class'=>'application.widgets.redactorjs.actions.ImageUpload',
                'uploadCreate' => true,
                'uploadPath' => Yii::app()->basePath.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'public'. DIRECTORY_SEPARATOR .'uploads',
             ),
            'imageList'=>'application.widgets.redactorjs.actions.ImageList',
            'uploadPath' => Yii::app()->basePath.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'public'. DIRECTORY_SEPARATOR .'uploads',
        );
    }
    
    
    public function beforeRender($view) 
    {
        $result = parent::beforeRender($view);
        Yii::app()->clientScript->registerCssFile(
            Yii::app()->baseUrl
                . '/css/blog.css'
        );
        return $result;
    }
    
	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$post=$this->loadModel();
		$comment=$this->newComment($post);

		$this->render('view',array(
			'model'=>$post,
			'comment'=>$comment,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

        $model->author_id=Yii::app()->user->id;
        
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$tag = Yii::app()->request->getParam('tag');
        $criteria=new CDbCriteria(array(
            'order'=>'create_time DESC',
            'with'=>'commentCount',
        ));
        
        if($tag) {
            $criteria->addSearchCondition('tags',$tag);
        }
        
        $dataProvider=new CActiveDataProvider('Post', array(
            'pagination'=>array(
                'pageSize'=>10,
            ),
            'criteria'=>$criteria,
        ));

        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
	}
    
    protected function newComment($post)
    {
        $comment=new Comment;

        if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
        {
            echo CActiveForm::validate($comment);
            Yii::app()->end();
        }

        if(isset($_POST['Comment']))
        {
            $comment->attributes=$_POST['Comment'];
            if($post->addComment($comment))
            {
//                if($comment->status==Comment::STATUS_PENDING)
                    Yii::app()->user->setFlash('commentSubmitted','Thank you for your comment. Your comment will be posted once it is approved.');
                $this->refresh();
            }
        }
        return $comment;
    }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Post the loaded model
	 * @throws CHttpException
	 */

    public function loadModel()
    {
        if($this->_model===null)
        {
            if(isset($_GET['id']))
            {
                $this->_model=Post::model()->findByPk($_GET['id']);
            }
            if($this->_model===null)
                throw new CHttpException(404,'Запрашиваемая страница не существует.');
        }
        return $this->_model;
    }
    
    /**
	 * Suggests tags based on the current user input.
	 * This is called via AJAX when the user is entering the tags input.
	 */
	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=Tag::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}
	
	
	/**
	 * Performs the AJAX validation.
	 * @param Post $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/post/_comments.php
<?php
$deleteJS = <<<DEL
$('.container').on('click','.time a.delete',function() {
	var th=$(this),
		container=th.closest('div.comment'),
		id=container.attr('id').slice(1);
        console.log(container);
	if(confirm('Are you sure you want to delete comment #'+id+'?')) {
		$.ajax({
			url:th.attr('href'),
			type:'POST'
		}).done(function(){container.slideUp()});
	}
	return false;
});
DEL;
Yii::app()->getClientScript()->registerScript('delete', $deleteJS);
?>

<?php foreach($comments as $comment): ?>
<?php $create_date = new DateTime($comment->create_time); ?>

<div class="comment" id="c<?php echo $comment->id; ?>">

	<?php echo CHtml::link("<span class='icon'></span>", $comment->getUrl($post), array(
		'class'=>'cid',
		'title'=>'Permalink to this comment',
	)); ?>

	<div class="author">
		<?php echo $comment->authorLink; ?> says:
	</div>

	<div class="time">
        <?php if (! Yii::app()->user->isGuest) {
            echo CHtml::link('Delete',array('comment/delete','id'=>$comment->id),array('class'=>'delete')); ?> |
            <?php } ?>
		<?php echo date_format($create_date, 'Y-m-d H:i:s'); ?>
	</div>

	<div class="content">
		<?php echo nl2br(CHtml::encode($comment->content)); ?>
	</div>

</div><!-- comment -->
<?php endforeach; ?>

protected/views/post/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm'); ?>
    
	<?php echo CHtml::errorSummary($model); ?>

    <div class="row">
		<?php echo CHtml::activeDropDownList($model,'author_id', array(
            Yii::app()->user->id => 'От своего имени',
            3 => 'Общее авторство',
        ) ); ?>
	</div>
    
	<div class="row">
		<?php //echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>80,'maxlength'=>128, 'class'=>'input-xxlarge',  'placeholder'=>'Название поста')); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php // echo CHtml::activeTextArea($model,'content',array('rows'=>10, 'cols'=>70)); 
        $attribute='content';
           $this->widget('application.widgets.redactorjs.Redactor', array(
               'model' => $model, 
               'attribute' => $attribute,
               //'toolbar' => 'mini',
               'lang'=>'ru',
               'editorOptions' => array(
                   'fileUpload'=>Yii::app()->createUrl('blog/fileUpload',array(
                        //'attr'=>$attribute
                    )),
                    'fileUploadErrorCallback'=>new CJavaScriptExpression(
                        'function(obj,json) { alert(json.error); }'
                    ),
                    'imageUpload'=>Yii::app()->createUrl('blog/imageUpload',array(
                       // 'attr'=>$attribute
                    )),
                    'imageGetJson'=>Yii::app()->createUrl('blog/imageList',array(
                       // 'attr'=>$attribute
                    )),
                    'imageUploadErrorCallback'=>new CJavaScriptExpression(
                        'function(obj,json) { alert(json.error); }'),
                   
                   ),
                )
           );
        ?>
        
		<?php echo $form->error($model,'content'); ?>
	</div>

	<div class="row tags-row">
		<?php //echo $form->labelEx($model,'tags'); ?>
        <div class="input-prepend">
            <span class="add-on">Tags</span>
            <?php $this->widget('CAutoComplete', array(
                'model'=>$model,
                'attribute'=>'tags',
                'url'=>array('suggestTags'),
                'multiple'=>true,
                'htmlOptions'=>array('size'=>50),
            )); ?>
        </div>
		<p class="hint">Пожалуйста, разделяйте теги запятыми.</p>
		<?php echo $form->error($model,'tags'); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Опубликовать' : 'Сохранить', array('class'=>'buttn')); ?>
	</div>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/post/_search.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tags'); ?>
		<?php echo $form->textArea($model,'tags',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_time'); ?>
		<?php echo $form->textField($model,'create_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author_id'); ?>
		<?php echo $form->textField($model,'author_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/post/_view.php
<?php 
    $update_date = new DateTime($data->update_time); 
?>

<div class="post">
    <div class="post-before">
        <span>Last updated on <?php echo date_format($update_date, 'Y-m-d H:i:s');; ?></span>
        <?php  echo CHtml::link('<span class="icon"></span>', $data->url, array('title'=>'permalink')); ?> 
    </div>
    <div class="post-view">
        <div class="post-info">
            <div class="author">
                <img src='<?php echo Yii::app()->baseUrl."/images/avatar/".$data->author->getAvatar() ?>'>
            </div>
        </div>
        <div class="post-content">
            <div class="post-title">
                <?php echo CHtml::link(CHtml::encode($data->title), $data->url); ?>
            </div>
            <div class="post-text">
                <?php
                        $this->beginWidget('CMarkdown', array('purifyOutput'=>false));
                        echo $data->content;
                        $this->endWidget();
                ?>
            </div>
        </div>
    </div>
    <div class="post-bottom">
        <div class="post-comments">
            <?php  
             if ($data->commentCount) {
                 echo CHtml::link("<span class='icon'></span> ({$data->commentCount})",$data->url.'#comments');
             } else {
                 echo CHtml::link("<span class='icon'></span>",$data->url.'#comments');
             } ?> 
        </div>
        <div class="tags">
            <?php if ($data->tagLinks) { 
                echo CHtml::tag('span', array('class'=>'icon'), null, true);
                echo implode(', ', $data->tagLinks);
            } ?>
        </div>
    </div>
</div>

protected/views/post/create.php
<?php $this->pageTitle='Create post'; ?>
<h1>Create Post</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/index.php
<?php if(!empty($_GET['tag'])) { ?>
<h1>Posts Tagged with <i><?php echo CHtml::encode($_GET['tag']); ?></i></h1>
<?php } else { ?>
<span class="big-icon big-blog"></span><h1>Our Blog</h1>
<?php } ?>

<?php
if (!Yii::app()->user->isGuest) {
    echo CHtml::link(Yii::t('app','Написать новый пост'), Yii::app()->createUrl('blog/create') , array('class'=>'post-button')); 
} ?>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
	'template'=>"{items}\n{pager}",
    'pager' => array(
        'header' => '',
        'htmlOptions' => array(
            'class' => 'post-pager'
        )
    ),
)); ?>

protected/views/post/update.php
<h1>Update <i><?php echo CHtml::encode($model->title); ?></i></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/view.php
<?php
$this->pageTitle=$model->title;
$update_date = new DateTime($model->update_time); 

?>

<div class="post">
    <div class="post-before">
        <span>Last updated on <?php echo date_format($update_date, 'Y-m-d H:i:s');; ?></span>
    </div>
    <div class="post-view">
        <div class="post-info">
            <div class="author">
                <img src='<?php echo Yii::app()->baseUrl."/images/avatar/".$model->author->getAvatar() ?>'>
            </div>
        </div>
        <div class="post-content">
            <div class="post-title">
                <?php echo CHtml::link(CHtml::encode($model->title), $model->url); ?>
            </div>
            <div class="post-text">
                <?php
                        $this->beginWidget('CMarkdown', array('purifyOutput'=>false));
                        echo $model->content;
                        $this->endWidget();
                ?>
            </div>
        </div>
    </div>
    <div class="post-bottom">
        <div class="tags">
            <?php if ($model->tagLinks) { 
                echo CHtml::tag('span', array('class'=>'icon'), null, true);
                echo implode(', ', $model->tagLinks);
            } ?>
        </div>
    </div>
</div>

<div id="comments">
	<?php if($model->commentCount>=1) { ?>
		<h3>
			<?php echo $model->commentCount>1 ? $model->commentCount . ' comments:' : 'One comment:'; ?>
		</h3>

		<?php $this->renderPartial('_comments',array(
			'post'=>$model,
			'comments'=>$model->comments,
		)); ?>
	<?php } ?>

	<h3>Leave a Comment</h3>

	<?php if(Yii::app()->user->hasFlash('commentSubmitted')): ?>
		<div class="flash-success">
			<?php echo Yii::app()->user->getFlash('commentSubmitted'); ?>
		</div>
	<?php else: ?>
		<?php $this->renderPartial('/comment/_form',array(
			'model'=>$comment,
		)); ?>
	<?php endif; ?>

</div><!-- comments -->